# Generated by Django 6.0.1 on 2026-02-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.IntegerField()),
                ('productDescription', models.TextField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='studentEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
