# Generated by Django 6.0.1 on 2026-02-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_product_productcolor_product_productstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=100)),
                ('branchSubject', models.CharField(max_length=100)),
                ('branchCredit', models.IntegerField()),
                ('branchCourseDuration', models.IntegerField()),
                ('branchCourseFee', models.IntegerField()),
            ],
            options={
                'db_table': 'branch',
            },
        ),
    ]
